WITH RECURSIVE cte AS (
    SELECT 0 AS n
    UNION ALL
    SELECT n + 1 FROM cte WHERE n < 23
)
SELECT n AS HOUR, IFNULL((SELECT COUNT(DATETIME) AS G FROM ANIMAL_OUTS WHERE HOUR(DATETIME)=N), 0) FROM cte GROUP BY N ORDER BY N
