SELECT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
JOIN (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE MONTH(START_DATE) = 10 GROUP BY CAR_ID) B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC
